wandb_version: 1

activation_function:
  value: silu
batch_normalization:
  value: false
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.3
filter_organisation:
  value: double
hidden_neurons:
  value: 1024
learning_rate:
  value: 0.0001
num_filters:
  value: 128
weight_decay:
  value: 0.0005
