wandb_version: 1

activation_function:
  value: silu
batch_normalization:
  value: false
batch_size:
  value: 128
data_aug:
  value: true
dropout:
  value: 0.3
filter_organisation:
  value: same
filter_size:
  value: 128
hidden_neurons:
  value: 2048
learning_rate:
  value: 2.0e-05
weight_decay:
  value: 5.0e-05
