wandb_version: 1

activation_function:
  value: relu
batch_normalization:
  value: true
batch_size:
  value: 128
data_aug:
  value: false
dropout:
  value: 0.3
filter_organisation:
  value: double
filter_size:
  value: 128
hidden_neurons:
  value: 1024
learning_rate:
  value: 1.0e-05
weight_decay:
  value: 0.0005
