wandb_version: 1

activation_function:
  value: gelu
batch_normalization:
  value: true
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.3
filter_organisation:
  value: double
filter_size:
  value: 64
hidden_neurons:
  value: 4192
learning_rate:
  value: 0.0001
weight_decay:
  value: 5.0e-05
