wandb_version: 1

activation_function:
  value: gelu
batch_normalization:
  value: true
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0.3
filter_organisation:
  value: half
filter_size:
  value: 64
hidden_neurons:
  value: 2048
learning_rate:
  value: 0.001
weight_decay:
  value: 0.0005
