wandb_version: 1

activation_function:
  value: silu
batch_normalization:
  value: true
batch_size:
  value: 128
data_aug:
  value: false
dropout:
  value: 0.3
filter_organisation:
  value: double
filter_size:
  value: 32
hidden_neurons:
  value: 2048
learning_rate:
  value: 0.001
weight_decay:
  value: 0.0005
