wandb_version: 1

activation_function:
  value: silu
batch_normalization:
  value: false
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0.2
filter_organisation:
  value: half
hidden_neurons:
  value: 4192
learning_rate:
  value: 0.0001
num_filters:
  value: 128
weight_decay:
  value: 0.0005
