_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "10":
                - 3
            "12": 0.19.9
            "13": linux-x86_64
activation_function:
    value: mish
batch_normalization:
    value: false
batch_size:
    value: 32
data_aug:
    value: false
dropout:
    value: 0.3
filter_organisation:
    value: same
filter_size:
    value: 64
hidden_neurons:
    value: 1024
learning_rate:
    value: 2e-05
weight_decay:
    value: 0
