wandb_version: 1

activation_function:
  value: leaky_relu
batch_normalization:
  value: false
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.2
filter_organisation:
  value: half
hidden_neurons:
  value: 1024
learning_rate:
  value: 0.0001
num_filters:
  value: 32
weight_decay:
  value: 5.0e-05
