wandb_version: 1

activation_function:
  value: mish
batch_normalization:
  value: false
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.2
filter_organisation:
  value: same
hidden_neurons:
  value: 4192
learning_rate:
  value: 0.0002
num_filters:
  value: 64
weight_decay:
  value: 5.0e-05
