wandb_version: 1

activation_function:
  value: gelu
batch_normalization:
  value: true
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0.2
filter_organisation:
  value: same
hidden_neurons:
  value: 4192
learning_rate:
  value: 1.0e-05
num_filters:
  value: 32
weight_decay:
  value: 0.0005
