wandb_version: 1

activation_function:
  value: leaky_relu
batch_normalization:
  value: false
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0.2
filter_organisation:
  value: same
hidden_neurons:
  value: 1024
learning_rate:
  value: 0.0002
num_filters:
  value: 32
weight_decay:
  value: 0
