wandb_version: 1

activation_function:
  value: gelu
batch_normalization:
  value: true
batch_size:
  value: 64
data_aug:
  value: false
dropout:
  value: 0.2
filter_organisation:
  value: double
hidden_neurons:
  value: 1024
learning_rate:
  value: 0.001
num_filters:
  value: 128
weight_decay:
  value: 5.0e-05
