wandb_version: 1

activation_function:
  value: gelu
batch_normalization:
  value: false
batch_size:
  value: 64
data_aug:
  value: true
dropout:
  value: 0.3
filter_organisation:
  value: same
hidden_neurons:
  value: 2048
learning_rate:
  value: 0.0001
num_filters:
  value: 64
weight_decay:
  value: 0.0005
