wandb_version: 1

activation_function:
  value: tanh
batch_normalization:
  value: false
batch_size:
  value: 32
data_aug:
  value: true
dropout:
  value: 0.2
filter_organisation:
  value: same
hidden_neurons:
  value: 2048
learning_rate:
  value: 1.0e-05
num_filters:
  value: 128
weight_decay:
  value: 0
