wandb_version: 1

activation_function:
  value: relu
batch_normalization:
  value: true
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.2
filter_organisation:
  value: same
hidden_neurons:
  value: 1024
learning_rate:
  value: 0.001
num_filters:
  value: 32
weight_decay:
  value: 0.0005
