wandb_version: 1

activation_function:
  value: leaky_relu
batch_normalization:
  value: false
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.3
filter_organisation:
  value: double
hidden_neurons:
  value: 4192
learning_rate:
  value: 0.0002
num_filters:
  value: 32
weight_decay:
  value: 0.0005
