wandb_version: 1

activation_function:
  value: tanh
batch_normalization:
  value: true
batch_size:
  value: 64
data_aug:
  value: true
dropout:
  value: 0.3
filter_organisation:
  value: double
hidden_neurons:
  value: 2048
learning_rate:
  value: 0.0002
num_filters:
  value: 32
weight_decay:
  value: 0
