wandb_version: 1

activation_function:
  value: selu
batch_normalization:
  value: false
batch_size:
  value: 64
data_aug:
  value: true
dropout:
  value: 0.2
filter_organisation:
  value: double
hidden_neurons:
  value: 1024
learning_rate:
  value: 0.0001
num_filters:
  value: 64
weight_decay:
  value: 0.0005
