wandb_version: 1

activation_function:
  value: relu
batch_normalization:
  value: false
batch_size:
  value: 32
data_aug:
  value: false
dropout:
  value: 0.3
filter_organisation:
  value: same
hidden_neurons:
  value: 4192
learning_rate:
  value: 0.0001
num_filters:
  value: 128
weight_decay:
  value: 5.0e-05
